version: '3'

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: simple_chat_web
    volumes:
      - ./client/dist:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - 80:80
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - client
      - db
      - api

  client:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: simple_chat_client
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    expose:
      - 3000
    command: sh -c "npm run build && npm run dev"
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - api
      - db
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: simple_chat_api
    working_dir: /app
    volumes:
      - ./api:/app
    expose:
      - 5100
    command: go run main.go
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - db

  db:
    build:
      context: mariadb
      dockerfile: Dockerfile
    container_name: simple_chat_db
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mariadb/db:/var/lib/mysql
      - ./mariadb/log:/var/log/mysql
      - ./mariadb/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=chat
      - MYSQL_PASSWORD=pass1234
      - MYSQL_DATABASE=chat
      - TZ=Asia/Tokyo

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db