version: '3'

services:
  nginx:
    image: simple_chat_web
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - ./client/dist:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - 80:80
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - client

  client:
    image: simple_chat_client
    build:
      context: client
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    expose:
      - 3000
    command: sh -c "npm run build && npm run dev"
    tty: true
    stdin_open: true
    restart: always
